include("shared.lua")
include("config/sh_config.lua")
include("core/sh_core.lua")
include("core/cl_core.lua")
include("core/sh_util.lua")
include("modules/economy/sh_economy.lua")
include("modules/economy/cl_economy.lua")
include("modules/economy/sh_business.lua")
include("modules/jobs/sh_jobs.lua")
include("modules/jobs/cl_jobs.lua")
include("modules/factions/sh_factions.lua")
include("modules/factions/cl_factions.lua")
include("modules/survival/sh_survival.lua")
include("modules/survival/cl_survival.lua")
include("lua/vgui/ajmrp_bio_ui.lua")
include("lua/vgui/ajmrp_cooking_ui.lua")
include("lua/vgui/ajmrp_trade_ui.lua")

function GM:Initialize()
    print("[AJMRP] Client initialized")
end